#============================= == == == == == ============
#dark_powered.toml-- - dark powered configuration example for SpaceVim
#Copyright(c) 2016 - 2017 Wang Shidong &Contributors
#Author : Wang Shidong < wsdjeg at 163.com>
#URL : https: // spacevim.org
#License : GPLv3
#============================================================
#All SpaceVim option below[option] section
# This is a basic configuration example for SpaceVim

# All SpaceVim options are below [options] snippet
[options]
    default_indent = 2
    expand_tab = true
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer, the value of this option is a string.
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors, the type of the value is boolean, true or false.
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_separator = "bar"
    buffer_index_type = 4
    # Display file type icon on the tabline, If you do not have nerd fonts
    # installed, please change the value to false
    enable_tabline_filetype_icon = false
    # Display current mode text on statusline, by default It is disabled,
    # only color will be changed when switch modes.
    # checkers options
    enable_statusline_mode = true
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

[[layers]]
    name = "core#banner" 

[[layers]]
    name = "core#statusline" 

[[layers]]
    name = "core#tabline" 

# Enable autocomplete layer
[[layers]]
    name = "autocomplete"
# auto_completion_return_key_behavior = "nil"
auto_completion_tab_key_behavior = "smart"
    auto_completion_delay = 200
    auto_completion_complete_with_key_sequence = "nil"
    auto_completion_complete_with_key_sequence_delay = 0.1
    # name = "autocomplete"
      auto-completion-return-key-behavior = "complete"
#    auto-completion-tab-key-behavior = "cycle"

[[layers]]
    name = "shell"
    default_position = "top"
    default_height = 30

# This is an example for adding custom plugins lilydjwg/colorizer
[[custom_plugins]]
    name = "vim-scripts/dbext.vim"
    merged = true
    
    name = "lilydjwg/colorizer"
    merged = true

    name = "junegunn/vim-github-dashboard"
    merged = true
    
    name = "kdheepak/JuliaFormatter.vim"
    merged = true

    name = "nono/jquery.vim"
    merged = true

    name = 'tibabit/vim-templates'
    merged = false
    
    name = 'aperezdc/vim-template'
    merged = true

    name = 'editorconfig/editorconfig-vim'
    merged = true

    name = 'tpope/vim-surround'
    merged = true

    name = 'scrooloose/nerdtree'
    merged = true

    name = 'scrooloose/syntastic'
    merged = true

    name = 'pangloss/vim-javascript'
    merged = true

    name = 'luchermitte/vimfold4c'
    merged = true

    name = 'shougo/neocomplete.vim'
    merged = true

[[layers]] 
    name = "lang#java"

[[layers]]
  name = "lang#php"

[[layers]] 
    name = "lang#html"

[[layers]]
    name = "lang#sh"

[[layers]] 
    name = "lang#python"
    python_file_head = [
      '#!/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
    ]
    enable_typeinfo = true

[[layers]] 
    name = "lang#javascript"
    auto_fix = true
    enable_flow_syntax = true

[[layers]] 
    name = "lang#perl"

[[layers]] 
    name = "lang#ruby"

[[layers]] 
    name = "lang#c"
    clang_executable = "/data/data/com.termux/files/usr/bin/clang"
    enable_clang_syntax_highlight = true
    [layer.clang_std]
    c = "c17"
    cpp = "c++20"

[[layers]] 
    name = "lang#r"
    repl_command = "R --no-save"

[[layers]] 
    name = "format"

[[layers]]
    name = "checkers"
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true

[[layers]] 
    name = 'shell' 
    default_position = 'top' 
    default_height = 30

[[layers]]
    name = "git"

[[layers]]
    name = "github"

[[layers]]
    name = "lang#latex"

[[layers]]
    name = "lang#markdown"

[[layers]]
    name = "ui"
    enable_sidebar = true

[[layers]]
    name = "sudo"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "lang#assembly"

[[layers]]
  name = "lang#csharp"
  highlight_types = 0

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#rust"
  recommended_style = true
  format_on_save = true

[[layers]]
  name = "lang#julia"

[[layers]]
  name = "lang#lisp"

[[layers]]
  name = "lang#sql"

[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lang#xquery"

[[layers]]
  name = "lang#groovy"

[[layers]]
  name = "lang#json"

[[layers]]
  name = "lang#d"
